### PR TITLE
replace all immutable & type.

### PR DESCRIPTION
**Pull request by DrKrar**

### CODE REVIEW

**Comment by DrKrar** [comment]
i think this will be useful when Julia v0.4 support is dropped.

**Comment by ararslan** [comment]
The package still supports 0.5, which does not recognize these keywords. I think we'll just have to live with the deprecation warnings in 0.7 until this package raises the minimum Julia version to 0.6.

**Comment by iamed2** [comment]
I can't see dropping 0.5 support until 1.0 comes out

**Comment by DrKrar** [comment]
I see. what about use of @compt to avoid deprecation warnings.

**Comment by ararslan** [comment]
`@compat` doesn't support `struct`/`mutable struct`

**Comment by iamed2** [comment]
And doesn't want to: https://github.com/JuliaLang/Compat.jl/pull/338

**Comment by martinholters** [comment]
Backward-compatible way of getting rid of the deprecation warnings would be what was done in JuliaLang/Compat.jl#362 - not exactly pretty, but works.

**Comment by DrKrar** [comment]
As I get to misunderstand, it is appropriate to close this PR.

**Pull request closed without merging**
